### ISSUE TITLE
Thaw breaks with optional dependencies

### ISSUE THREAD

**Issue by nkuttler** [kateapault/pip-thaw#5]
A requirement with optional dependencies like ```tablib[xls,xlsx]==2.0.0``` doesn't seem to be handled and throws an exception:

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/path/to/virtualenv/lib/python3.8/site-packages/thaw/__main__.py", line 7, in <module>
    run()
  File "/path/to/virtualenv/lib/python3.8/site-packages/thaw/__main__.py", line 4, in run
    thaw.main()
  File "/path/to/virtualenv/lib/python3.8/site-packages/thaw/thaw.py", line 340, in main
    latest_version = get_latest_version(library)
  File "/path/to/virtualenv/lib/python3.8/site-packages/thaw/thaw.py", line 147, in get_latest_version
    result = request.urlopen(url)
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

**Comment by kateapault** [comment]
I just pushed a new version that should work for optional dependencies - please let me know if it works! 

If it doesn't, are you able to link me to some of the repos thaw is breaking on so I can get a better look at what's missing from thaw and/or going wrong?

**Comment by nkuttler** [comment]
Thank you, but I still can't run the code because of the other issue.

If you parse versions yourself in your code may I suggest you take a look at https://github.com/pypa/pip/blob/master/src/pip/_internal/req/req_file.py#L281

Haven't worked with that code myself, but it might be useful to parse pip files.
